---
engines:
  flake8:
    enabled: true
exclude_paths:
  - "pyproject.toml"
  - "setup.py"
  - "versioneer.py"
  - "genconf.py"
  - "ams/pypower/**"
  - "ams/_version.py"
  - ".github/**"
  - "README.md"
  - "CODE_OF_CONDUCT.md"
  - "tests/**"
  - "docs/**"
  - "examples/**"