coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

cli:
  plugins:
    pycoverage:
      report_type: "xml"

ignore:
  - "ams/_version.py"
  - "ams/pypower/**"