coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

cli:
  plugins:
    pycoverage:
      report_type: "xml"

ignore:
  - "setup.py"
  - "versioneer.py"
  - "ams/pypower/**"
  - "ams/_version.py"
  - ".github/**"
  - "README.md"
  - "tests/**"