coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

cli:
  plugins:
    pycoverage:
      report_type: "xml"

codecov: 
  token: 5fc2d41f-bcba-455d-a843-f85beb76d28f
ignore:
  - "setup.py"
  - "versioneer.py"
  - "ams/pypower/**"
  - "ams/_version.py"
  - ".github/**"
  - "README.md"
  - "CODE_OF_CONDUCT.md"
  - "tests/**"
  - "docs/**"