coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

cli:
  plugins:
    pycoverage:
      report_type: "xml"

codecov: 
  token: ${{ secrets.CODECOV_GLOBAL }}
ignore:
  - "pyproject.toml"
  - "setup.py"
  - "genconf.py"
  - "versioneer.py"
  - "ams/_version.py"
  - ".github/**"
  - "README.md"
  - "CODE_OF_CONDUCT.md"
  - "tests/**"
  - "docs/**"
  - "examples/**"