[project]
name = "ams"

version = "0.4.0"

description = "Python software for dispatch modeling and co-simulation with dynanic"

readme = "README.md"

requires-python = ">=3.8"

license = {file = "LICENSE"}

authors = [
  { name="Jinning Wang", email="jinninggm@gmail.com"},
]
maintainers = [
  {name="Jinning Wang", email="jinninggm@gmail.com"}
]

keywords = ["optimal power flow", "dispatch", "power system analysis", "curent", "curent ltb"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

dependencies = [
  "numpy"
  "scipy"
  "pandas"
  "matplotlib"
  "psutil"
]

[project.optional-dependencies]
dev = [
 "pytest==7.0.1"
 "flake8"
 "sphinx==4.5.0"
 "pydata-sphinx-theme"
 "numpydoc"
 "sphinx-copybutton"
 "sphinx-panels"
 "pydata-sphinx-theme"
 "myst-parser==0.15.2"
 "myst-nb==0.13.2"
]

[project.urls]
homepage = "https://github.com/jinningwang/ams"
documentation = "https://ams.readthedocs.io/en/latest/"
repository = "https://github.com/jinningwang/ams"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
