name: Codacy Coverage Reporter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret presence
        id: check_secret
        run: |
          echo "is_set=false" >> $GITHUB_OUTPUT
          if [ ! -z "${{ secrets.CODACY_PROJECT_TOKEN }}" ]; then
            echo "is_set=true" >> $GITHUB_OUTPUT
          fi

      - name: Conditional run codacy-coverage-reporter
        if: steps.check_secret.outputs.is_set == 'true'
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}