name: Codebase visualizer

on: [push, pull_request]

jobs:
  update_diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create a new branch
        run: |
          git branch update-diagram
          git checkout update-diagram

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github,ams/pypower,ams/_version.py"
          root_path: "ams/"
          output_file: "docs/source/images/diagram.svg"

      - name: Commit and push if there are changes
        run: |
          git add docs/images/diagram.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update codebase diagram"
            # Retry push up to 3 times in case of failure
            MAX_RETRIES=3
            for attempt in $(seq 1 $MAX_RETRIES); do
              echo "Attempting to push (Attempt $attempt of $MAX_RETRIES)..."
              git push --set-upstream origin update-diagram && break || echo "Push failed, retrying..."
              if [ "$attempt" -lt "$MAX_RETRIES" ]; then
                sleep 5 # Wait for 5 seconds before retrying
              else
                echo "Push failed after $MAX_RETRIES attempts."
                exit 1 # Exit with error if the push fails after max retries
              fi
            done
          fi

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: "update-diagram"
          destination_branch: "develop" # or master, depending on your workflow
          pr_title: "Update codebase diagram"
          pr_body: "Automatically generated PR to update codebase diagram"
          pr_label: "automated pr" # Add any labels you want for these PRs