name: Python application

on: [push, pull_request]

jobs:
  build:
    name: Codecov
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        mamba-version: "*"
        miniforge-version: "latest"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
    - shell: bash -el {0}
      name: Install dependencies
      run: |
        mamba install -y nbmake pytest-xdist line_profiler  # add'l packages for notebook tests.
        mamba install --file requirements.txt --file requirements-extra.txt
        python -m pip install -e .
    - shell: bash -el {0}
      name: Test with pytest and collect coverage
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}