name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
          mamba-version: "*"
          miniforge-version: "latest"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - shell: bash -el {0}
        name: Install dependencies
        run: |
          mamba install --file requirements.txt --file requirements-dev.txt
          python -m pip install -e .
      - shell: bash -el {0}
        name: Test with pytest
        run: |
          pytest
      - name: Build a distribution if tagged
        run: |
          python -m build
      - name: Publish a Python distribution to PyPI if tagged
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}