name: Python application

on: [push, pull_request]

jobs:
  build:
    name: AMS Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, 3.10, 3.11, 3.12]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.11
        mamba-version: "*"
        miniforge-version: "latest"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
    - shell: bash -el {0}
      name: Install dependencies
      run: |
        mamba install -y nbmake pytest-xdist line_profiler  # add'l packages for notebook tests.
        mamba install --file requirements.txt --file requirements-extra.txt
        python -m pip install -e .
    - name: Lint with flake8 for pull requests
      if: github.event_name == 'pull_request'
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 .
    - shell: bash -el {0}
      name: Test with pytest
      run: |
        pytest
    - shell: bash -el {0}
      name: Test notebooks.
      run: |
        pytest --nbmake examples --ignore=examples/demonstration
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    # - name: Build a distribution if tagged
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    #   run: |
    #     python setup.py sdist
    # - name: Publish a Python distribution to PyPI if tagged
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     user: __token__
    #     password: ${{ secrets.pypi_password }}
