name: Zenodo Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download archive to runner
        env:
          TARBALL_URL: ${{ github.event.release.tarball_url }}
        run: |
          set -euo pipefail
          # If repo is private, uncomment the header line below and remove the line without -H
          # curl -L -H "Authorization: token ${{ github.token }}" "$TARBALL_URL" -o source.tar.gz
          curl -L "$TARBALL_URL" -o source.tar.gz
          echo "archive=source.tar.gz" >> $GITHUB_ENV

      - name: Run Zenodo Deploy
        uses: ./
        id: deploy
        with:
          version: ${{ github.event.release.tag_name }}
          zenodo_json: .zenodo.json
          archive: ${{ env.archive }}
          token: ${{ secrets.ZENODO_TOKEN }}
          doi: 10.1109/TSTE.2025.3528027

      - name: View Outputs
        env:
          doi: ${{ steps.deploy.outputs.doi }}
          conceptdoi: ${{ steps.deploy.outputs.conceptdoi }}
          conceptbadge: ${{ steps.deploy.outputs.conceptbadge }}
          badge: ${{ steps.deploy.outputs.badge }}
          bucket: ${{ steps.deploy.outputs.bucket }}
          latest: ${{ steps.deploy.outputs.latest }}
          latest_html: ${{ steps.deploy.outputs.latest_html }}
          record: ${{ steps.deploy.outputs.record }}
          record_html: ${{ steps.deploy.outputs.record_html }}
        run: |
          echo "doi ${doi}"
          echo "conceptdoi ${conceptdoi}"
          echo "conceptbadge ${conceptbadge}"
          echo "badge ${badge}"
          echo "bucket ${bucket}"
          echo "latest ${latest}"
          echo "latest html ${latest_html}"
          echo "record ${record}"
          echo "record html ${record_html}"